[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.11.0"
strum = "0.25.0"
strum_macros = "0.25.1"
ptree = "0.4"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "1_calorie_counting"
harness = false